#!/bin/sh

# === Variables ===
distro_name=$(lsb_release -is)

# Define custom directories
ZSH_CUSTOM=$HOME/.oh-my-zsh/custom
NVIM_CONFIG=$HOME/.config/nvim
FZF_DIR=$HOME/.fzf
TMUX_PLUGIN_DIR=$HOME/.tmux/plugins/tpm
YADM_DIR=$HOME/.config/yadm

confirm() {
    while true; do
        read -p "$1 (y/n): " yn
        case $yn in
            [Yy]* ) return 0;;
            [Nn]* ) return 1;;
            * ) echo "Please answer y (yes) or n (no).";;
        esac
    done
}


### INSTALLATION ###

cd
if [ $distro_name = 'EndeavourOS' ]; then
    if confirm "Do you want to update the package database and the system?"; then
        sudo pacman -Syyu --noconfirm
    else
        echo "Skipping system update."
    fi
    sudo pacman -S --needed --noconfirm  $(< $YADM_DIR/packages.txt)
    yay -S --needed --noconfirm  $(< $YADM_DIR/yay_packages.txt)
    sudo pacman -Rsn $(pacman -Qdtq) --noconfirm
elif [ $distro_name = 'Fedora' ]; then
    if confirm "Do you want to update the package database and the system?"; then
        sudo dnf -y update
    else
        echo "Skipping system update."
    fi
    sudo dnf install -y $(< packages.txt)
    sudo dnf autoremove -y
fi

# Update font cache
fc-cache

# Notify the user that the script has finished
echo "=== Packages Intallation completed. ==="

### MANUAL INSTALATIONS ###

echo "### Starting manual installations ###"

echo "Preparing git & github"
gh auth login
gh auth setup-git

# Zinit
bash -c "$(curl --fail --show-error --silent --location https://raw.githubusercontent.com/zdharma-continuum/zinit/HEAD/scripts/install.sh)"

# FZF
if [ ! -d "$FZF_DIR" ]; then
    git clone --depth 1 https://github.com/junegunn/fzf.git $FZF_DIR
    $FZF_DIR/install --all
fi

# NVM
if [ ! -d "$HOME/.nvm" ]; then
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | sh
fi

# lazyvim
if [ ! -d "$NVIM_CONFIG" ]; then
  git clone https://github.com/LazyVim/starter $NVIM_CONFIG
  rm -rf ~/.config/nvim/.git
  
fi

# TMUX plugins
if [ ! -d "$TMUX_PLUGIN_DIR" ]; then
    git clone https://github.com/tmux-plugins/tpm $TMUX_PLUGIN_DIR
fi

# Miniconda
mkdir -p ~/miniconda3
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
rm -rf ~/miniconda3/miniconda.sh

# Exercism
wget https://github.com/exercism/cli/releases/download/v3.4.0/exercism-3.4.0-linux-x86_64.tar.gz
tar -xf exercism-3.4.0-linux-x86_64.tar.gz
mkdir -p ~/bin
mv exercism ~/bin
~/bin/exercism
echo 'export PATH=~/bin:$PATH' >> ~/.bash_profile
source ~/.bash_profile